// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

/*
 * @Author: calmwu
 * @Date: 2020-03-07 15:55:24
 * @Last Modified by: calmwu
 * @Last Modified time: 2020-03-07 16:35:23
 */

package main

import "sort"

// SortedSliceWrap
type MovieSliceWrap struct {
	Ssot        []*Movie
	CompareFunc func(left, right *Movie) bool
}

// Len 长度
func (ssw MovieSliceWrap) Len() int { return len(ssw.Ssot) }

// Swap 交换
func (ssw MovieSliceWrap) Swap(i, j int) { ssw.Ssot[i], ssw.Ssot[j] = ssw.Ssot[j], ssw.Ssot[i] }

// Less 比较
func (ssw MovieSliceWrap) Less(i, j int) bool {
	return ssw.CompareFunc(ssw.Ssot[i], ssw.Ssot[j])
}

// Sort 排序
func (ssw MovieSliceWrap) Sort() {
	sort.Sort(ssw)
}
