// Code generated by "stringer -type FinanceUpdateBusinessType"; DO NOT EDIT.

package proto

import "fmt"

const _FinanceUpdateBusinessType_name = "E_UPDATEBUSINESS_COMMONSHOPE_UPDATEBUSINESS_BREAKOUTSHOPE_UPDATEBUSINESS_SIGIN"

var _FinanceUpdateBusinessType_index = [...]uint8{0, 27, 56, 78}

func (i FinanceUpdateBusinessType) String() string {
	if i < 0 || i >= FinanceUpdateBusinessType(len(_FinanceUpdateBusinessType_index)-1) {
		return fmt.Sprintf("FinanceUpdateBusinessType(%d)", i)
	}
	return _FinanceUpdateBusinessType_name[_FinanceUpdateBusinessType_index[i]:_FinanceUpdateBusinessType_index[i+1]]
}
