// Code generated by "stringer -type GamePayType"; DO NOT EDIT.

package proto

import "fmt"

const _GamePayType_name = "E_GAMEPAY_GOLDE_GAMEPAY_DIAMONDE_GAMEPAY_HONORE_GAMEPAY_SHIPSOUL"

var _GamePayType_index = [...]uint8{0, 14, 31, 46, 64}

func (i GamePayType) String() string {
	if i < 0 || i >= GamePayType(len(_GamePayType_index)-1) {
		return fmt.Sprintf("GamePayType(%d)", i)
	}
	return _GamePayType_name[_GamePayType_index[i]:_GamePayType_index[i+1]]
}
