// Code generated by "stringer --type=RechargeCommodityType"; DO NOT EDIT.

package proto

import "fmt"

const _RechargeCommodityType_name = "E_RECHARGECOMMODITY_DIAMONDSE_RECHARGECOMMODITY_NORMALMONTHLYCARDE_RECHARGECOMMODITY_LUXURYMONTHLYCARDE_RECHARGECOMMODITY_SUPERGIFT"

var _RechargeCommodityType_index = [...]uint8{0, 28, 65, 102, 131}

func (i RechargeCommodityType) String() string {
	if i < 0 || i >= RechargeCommodityType(len(_RechargeCommodityType_index)-1) {
		return fmt.Sprintf("RechargeCommodityType(%d)", i)
	}
	return _RechargeCommodityType_name[_RechargeCommodityType_index[i]:_RechargeCommodityType_index[i+1]]
}
