// Code generated by "stringer -type ResourceCommodityType"; DO NOT EDIT.

package proto

import "fmt"

const _ResoruceCommodityType_name = "E_RESOURCECOMMODITY_GOLDE_RESOURCECOMMODITY_WOODE_RESOURCECOMMODITY_STONEE_RESOURCECOMMODITY_IRON"

var _ResoruceCommodityType_index = [...]uint8{0, 24, 48, 73, 97}

func (i ResourceCommodityType) String() string {
	if i < 0 || i >= ResourceCommodityType(len(_ResoruceCommodityType_index)-1) {
		return fmt.Sprintf("ResourceCommodityType(%d)", i)
	}
	return _ResoruceCommodityType_name[_ResoruceCommodityType_index[i]:_ResoruceCommodityType_index[i+1]]
}
