// Code generated by "stringer -type ShopCommodityType"; DO NOT EDIT.

package proto

import "fmt"

const _ShopCommodityType_name = "E_SHOPCOMMODITY_RECHARGEE_SHOPCOMMODITY_RESOURCEE_SHOPCOMMODITY_CARDPACK"

var _ShopCommodityType_index = [...]uint8{0, 24, 48, 72}

func (i ShopCommodityType) String() string {
	if i < 0 || i >= ShopCommodityType(len(_ShopCommodityType_index)-1) {
		return fmt.Sprintf("ShopCommodityType(%d)", i)
	}
	return _ShopCommodityType_name[_ShopCommodityType_index[i]:_ShopCommodityType_index[i+1]]
}
