// Code generated by "stringer -type=ProtoC2SCmd"; DO NOT EDIT.

package protocol

import "fmt"

const _ProtoC2SCmd_name = "E_C2S_CMD_SYNE_S2C_CMD_ASYNE_C2S_CMD_ACKE_C2S_TRANSFERE_S2C_TRANSFERE_C2S_HEARTBEATE_S2C_HEARTBEAT"

var _ProtoC2SCmd_index = [...]uint8{0, 13, 27, 40, 54, 68, 83, 98}

func (i ProtoC2SCmd) String() string {
	if i < 0 || i >= ProtoC2SCmd(len(_ProtoC2SCmd_index)-1) {
		return fmt.Sprintf("ProtoC2SCmd(%d)", i)
	}
	return _ProtoC2SCmd_name[_ProtoC2SCmd_index[i]:_ProtoC2SCmd_index[i+1]]
}
