// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_hs.proto

/*
Package protocol is a generated protocol buffer package.

import "google/protobuf/descriptor.proto";

It is generated from these files:
	proto_hs.proto

It has these top-level messages:
	ProtoSyn
	ProtoAsyn
	ProtoAck
	ProtoHeartBeat
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtoSyn struct {
	VerifyBuf      []byte `protobuf:"bytes,1,opt,name=VerifyBuf,proto3" json:"VerifyBuf,omitempty"`
	DHClientPubKey []byte `protobuf:"bytes,2,opt,name=DHClientPubKey,proto3" json:"DHClientPubKey,omitempty"`
}

func (m *ProtoSyn) Reset()                    { *m = ProtoSyn{} }
func (m *ProtoSyn) String() string            { return proto.CompactTextString(m) }
func (*ProtoSyn) ProtoMessage()               {}
func (*ProtoSyn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoSyn) GetVerifyBuf() []byte {
	if m != nil {
		return m.VerifyBuf
	}
	return nil
}

func (m *ProtoSyn) GetDHClientPubKey() []byte {
	if m != nil {
		return m.DHClientPubKey
	}
	return nil
}

type ProtoAsyn struct {
	DHServerPubKey []byte `protobuf:"bytes,1,opt,name=DHServerPubKey,proto3" json:"DHServerPubKey,omitempty"`
}

func (m *ProtoAsyn) Reset()                    { *m = ProtoAsyn{} }
func (m *ProtoAsyn) String() string            { return proto.CompactTextString(m) }
func (*ProtoAsyn) ProtoMessage()               {}
func (*ProtoAsyn) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtoAsyn) GetDHServerPubKey() []byte {
	if m != nil {
		return m.DHServerPubKey
	}
	return nil
}

type ProtoAck struct {
	CipherText []byte `protobuf:"bytes,1,opt,name=CipherText,proto3" json:"CipherText,omitempty"`
}

func (m *ProtoAck) Reset()                    { *m = ProtoAck{} }
func (m *ProtoAck) String() string            { return proto.CompactTextString(m) }
func (*ProtoAck) ProtoMessage()               {}
func (*ProtoAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProtoAck) GetCipherText() []byte {
	if m != nil {
		return m.CipherText
	}
	return nil
}

type ProtoHeartBeat struct {
	Timestamp int64 `protobuf:"fixed64,1,opt,name=Timestamp" json:"Timestamp,omitempty"`
}

func (m *ProtoHeartBeat) Reset()                    { *m = ProtoHeartBeat{} }
func (m *ProtoHeartBeat) String() string            { return proto.CompactTextString(m) }
func (*ProtoHeartBeat) ProtoMessage()               {}
func (*ProtoHeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProtoHeartBeat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*ProtoSyn)(nil), "protocol.ProtoSyn")
	proto.RegisterType((*ProtoAsyn)(nil), "protocol.ProtoAsyn")
	proto.RegisterType((*ProtoAck)(nil), "protocol.ProtoAck")
	proto.RegisterType((*ProtoHeartBeat)(nil), "protocol.ProtoHeartBeat")
}

func init() { proto.RegisterFile("proto_hs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x8f, 0xcf, 0x28, 0xd6, 0x03, 0x33, 0x84, 0x38, 0xc0, 0x54, 0x72, 0x7e, 0x8e, 0x52, 0x00,
	0x17, 0x47, 0x00, 0x88, 0x1d, 0x5c, 0x99, 0x27, 0x24, 0xc3, 0xc5, 0x19, 0x96, 0x5a, 0x94, 0x99,
	0x56, 0xe9, 0x54, 0x9a, 0x26, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x13, 0x84, 0x10, 0x10, 0x52, 0xe3,
	0xe2, 0x73, 0xf1, 0x70, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x09, 0x28, 0x4d, 0xf2, 0x4e, 0xad, 0x94,
	0x60, 0x02, 0x2b, 0x41, 0x13, 0x55, 0x32, 0xe6, 0xe2, 0x04, 0x9b, 0xe8, 0x58, 0x5c, 0x99, 0x07,
	0xd1, 0x14, 0x9c, 0x5a, 0x54, 0x96, 0x5a, 0x04, 0xd5, 0xc4, 0x08, 0xd3, 0x84, 0x2c, 0xaa, 0xa4,
	0x05, 0x75, 0x86, 0x63, 0x72, 0xb6, 0x90, 0x1c, 0x17, 0x97, 0x73, 0x66, 0x41, 0x46, 0x6a, 0x51,
	0x48, 0x6a, 0x45, 0x09, 0x54, 0x3d, 0x92, 0x88, 0x92, 0x1e, 0x17, 0x1f, 0x58, 0xad, 0x47, 0x6a,
	0x62, 0x51, 0x89, 0x53, 0x6a, 0x62, 0x09, 0xc8, 0xe1, 0x21, 0x99, 0xb9, 0xa9, 0xc5, 0x25, 0x89,
	0xb9, 0x05, 0x60, 0x0d, 0x02, 0x41, 0x08, 0x81, 0x24, 0x36, 0xb0, 0x67, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xd7, 0x04, 0xb0, 0x93, 0x05, 0x01, 0x00, 0x00,
}
