// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_hs.proto

#include "proto_hs.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace protocol {
class ProtoSynDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtoSyn>
      _instance;
} _ProtoSyn_default_instance_;
class ProtoAsynDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtoAsyn>
      _instance;
} _ProtoAsyn_default_instance_;
class ProtoAckDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtoAck>
      _instance;
} _ProtoAck_default_instance_;
class ProtoHeartBeatDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ProtoHeartBeat>
      _instance;
} _ProtoHeartBeat_default_instance_;
}  // namespace protocol
namespace protobuf_proto_5fhs_2eproto {
void InitDefaultsProtoSynImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::protocol::_ProtoSyn_default_instance_;
    new (ptr) ::protocol::ProtoSyn();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::ProtoSyn::InitAsDefaultInstance();
}

void InitDefaultsProtoSyn() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsProtoSynImpl);
}

void InitDefaultsProtoAsynImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::protocol::_ProtoAsyn_default_instance_;
    new (ptr) ::protocol::ProtoAsyn();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::ProtoAsyn::InitAsDefaultInstance();
}

void InitDefaultsProtoAsyn() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsProtoAsynImpl);
}

void InitDefaultsProtoAckImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::protocol::_ProtoAck_default_instance_;
    new (ptr) ::protocol::ProtoAck();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::ProtoAck::InitAsDefaultInstance();
}

void InitDefaultsProtoAck() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsProtoAckImpl);
}

void InitDefaultsProtoHeartBeatImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::protocol::_ProtoHeartBeat_default_instance_;
    new (ptr) ::protocol::ProtoHeartBeat();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protocol::ProtoHeartBeat::InitAsDefaultInstance();
}

void InitDefaultsProtoHeartBeat() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsProtoHeartBeatImpl);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::ProtoSyn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::ProtoSyn, verifybuf_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::ProtoSyn, dhclientpubkey_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::ProtoAsyn, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::ProtoAsyn, dhserverpubkey_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::ProtoAck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::ProtoAck, ciphertext_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::ProtoHeartBeat, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protocol::ProtoHeartBeat, timestamp_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protocol::ProtoSyn)},
  { 7, -1, sizeof(::protocol::ProtoAsyn)},
  { 13, -1, sizeof(::protocol::ProtoAck)},
  { 19, -1, sizeof(::protocol::ProtoHeartBeat)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::protocol::_ProtoSyn_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protocol::_ProtoAsyn_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protocol::_ProtoAck_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protocol::_ProtoHeartBeat_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "proto_hs.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\016proto_hs.proto\022\010protocol\"5\n\010ProtoSyn\022\021"
      "\n\tVerifyBuf\030\001 \001(\014\022\026\n\016DHClientPubKey\030\002 \001("
      "\014\"#\n\tProtoAsyn\022\026\n\016DHServerPubKey\030\001 \001(\014\"\036"
      "\n\010ProtoAck\022\022\n\nCipherText\030\001 \001(\014\"#\n\016ProtoH"
      "eartBeat\022\021\n\tTimestamp\030\001 \001(\020b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 195);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "proto_hs.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_proto_5fhs_2eproto
namespace protocol {

// ===================================================================

void ProtoSyn::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtoSyn::kVerifyBufFieldNumber;
const int ProtoSyn::kDHClientPubKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtoSyn::ProtoSyn()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_5fhs_2eproto::InitDefaultsProtoSyn();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.ProtoSyn)
}
ProtoSyn::ProtoSyn(const ProtoSyn& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  verifybuf_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.verifybuf().size() > 0) {
    verifybuf_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.verifybuf_);
  }
  dhclientpubkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.dhclientpubkey().size() > 0) {
    dhclientpubkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dhclientpubkey_);
  }
  // @@protoc_insertion_point(copy_constructor:protocol.ProtoSyn)
}

void ProtoSyn::SharedCtor() {
  verifybuf_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dhclientpubkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

ProtoSyn::~ProtoSyn() {
  // @@protoc_insertion_point(destructor:protocol.ProtoSyn)
  SharedDtor();
}

void ProtoSyn::SharedDtor() {
  verifybuf_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dhclientpubkey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ProtoSyn::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProtoSyn::descriptor() {
  ::protobuf_proto_5fhs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_5fhs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ProtoSyn& ProtoSyn::default_instance() {
  ::protobuf_proto_5fhs_2eproto::InitDefaultsProtoSyn();
  return *internal_default_instance();
}

ProtoSyn* ProtoSyn::New(::google::protobuf::Arena* arena) const {
  ProtoSyn* n = new ProtoSyn;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ProtoSyn::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.ProtoSyn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  verifybuf_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dhclientpubkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ProtoSyn::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.ProtoSyn)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes VerifyBuf = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_verifybuf()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes DHClientPubKey = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_dhclientpubkey()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.ProtoSyn)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.ProtoSyn)
  return false;
#undef DO_
}

void ProtoSyn::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.ProtoSyn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes VerifyBuf = 1;
  if (this->verifybuf().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->verifybuf(), output);
  }

  // bytes DHClientPubKey = 2;
  if (this->dhclientpubkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->dhclientpubkey(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.ProtoSyn)
}

::google::protobuf::uint8* ProtoSyn::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protocol.ProtoSyn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes VerifyBuf = 1;
  if (this->verifybuf().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->verifybuf(), target);
  }

  // bytes DHClientPubKey = 2;
  if (this->dhclientpubkey().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->dhclientpubkey(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.ProtoSyn)
  return target;
}

size_t ProtoSyn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.ProtoSyn)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes VerifyBuf = 1;
  if (this->verifybuf().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->verifybuf());
  }

  // bytes DHClientPubKey = 2;
  if (this->dhclientpubkey().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->dhclientpubkey());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProtoSyn::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.ProtoSyn)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtoSyn* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ProtoSyn>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.ProtoSyn)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.ProtoSyn)
    MergeFrom(*source);
  }
}

void ProtoSyn::MergeFrom(const ProtoSyn& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.ProtoSyn)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.verifybuf().size() > 0) {

    verifybuf_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.verifybuf_);
  }
  if (from.dhclientpubkey().size() > 0) {

    dhclientpubkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dhclientpubkey_);
  }
}

void ProtoSyn::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.ProtoSyn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtoSyn::CopyFrom(const ProtoSyn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.ProtoSyn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoSyn::IsInitialized() const {
  return true;
}

void ProtoSyn::Swap(ProtoSyn* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtoSyn::InternalSwap(ProtoSyn* other) {
  using std::swap;
  verifybuf_.Swap(&other->verifybuf_);
  dhclientpubkey_.Swap(&other->dhclientpubkey_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ProtoSyn::GetMetadata() const {
  protobuf_proto_5fhs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_5fhs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ProtoAsyn::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtoAsyn::kDHServerPubKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtoAsyn::ProtoAsyn()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_5fhs_2eproto::InitDefaultsProtoAsyn();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.ProtoAsyn)
}
ProtoAsyn::ProtoAsyn(const ProtoAsyn& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  dhserverpubkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.dhserverpubkey().size() > 0) {
    dhserverpubkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dhserverpubkey_);
  }
  // @@protoc_insertion_point(copy_constructor:protocol.ProtoAsyn)
}

void ProtoAsyn::SharedCtor() {
  dhserverpubkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

ProtoAsyn::~ProtoAsyn() {
  // @@protoc_insertion_point(destructor:protocol.ProtoAsyn)
  SharedDtor();
}

void ProtoAsyn::SharedDtor() {
  dhserverpubkey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ProtoAsyn::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProtoAsyn::descriptor() {
  ::protobuf_proto_5fhs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_5fhs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ProtoAsyn& ProtoAsyn::default_instance() {
  ::protobuf_proto_5fhs_2eproto::InitDefaultsProtoAsyn();
  return *internal_default_instance();
}

ProtoAsyn* ProtoAsyn::New(::google::protobuf::Arena* arena) const {
  ProtoAsyn* n = new ProtoAsyn;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ProtoAsyn::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.ProtoAsyn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  dhserverpubkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ProtoAsyn::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.ProtoAsyn)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes DHServerPubKey = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_dhserverpubkey()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.ProtoAsyn)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.ProtoAsyn)
  return false;
#undef DO_
}

void ProtoAsyn::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.ProtoAsyn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes DHServerPubKey = 1;
  if (this->dhserverpubkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->dhserverpubkey(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.ProtoAsyn)
}

::google::protobuf::uint8* ProtoAsyn::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protocol.ProtoAsyn)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes DHServerPubKey = 1;
  if (this->dhserverpubkey().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->dhserverpubkey(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.ProtoAsyn)
  return target;
}

size_t ProtoAsyn::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.ProtoAsyn)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes DHServerPubKey = 1;
  if (this->dhserverpubkey().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->dhserverpubkey());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProtoAsyn::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.ProtoAsyn)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtoAsyn* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ProtoAsyn>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.ProtoAsyn)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.ProtoAsyn)
    MergeFrom(*source);
  }
}

void ProtoAsyn::MergeFrom(const ProtoAsyn& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.ProtoAsyn)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.dhserverpubkey().size() > 0) {

    dhserverpubkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dhserverpubkey_);
  }
}

void ProtoAsyn::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.ProtoAsyn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtoAsyn::CopyFrom(const ProtoAsyn& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.ProtoAsyn)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoAsyn::IsInitialized() const {
  return true;
}

void ProtoAsyn::Swap(ProtoAsyn* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtoAsyn::InternalSwap(ProtoAsyn* other) {
  using std::swap;
  dhserverpubkey_.Swap(&other->dhserverpubkey_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ProtoAsyn::GetMetadata() const {
  protobuf_proto_5fhs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_5fhs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ProtoAck::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtoAck::kCipherTextFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtoAck::ProtoAck()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_5fhs_2eproto::InitDefaultsProtoAck();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.ProtoAck)
}
ProtoAck::ProtoAck(const ProtoAck& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ciphertext_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ciphertext().size() > 0) {
    ciphertext_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ciphertext_);
  }
  // @@protoc_insertion_point(copy_constructor:protocol.ProtoAck)
}

void ProtoAck::SharedCtor() {
  ciphertext_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

ProtoAck::~ProtoAck() {
  // @@protoc_insertion_point(destructor:protocol.ProtoAck)
  SharedDtor();
}

void ProtoAck::SharedDtor() {
  ciphertext_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ProtoAck::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProtoAck::descriptor() {
  ::protobuf_proto_5fhs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_5fhs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ProtoAck& ProtoAck::default_instance() {
  ::protobuf_proto_5fhs_2eproto::InitDefaultsProtoAck();
  return *internal_default_instance();
}

ProtoAck* ProtoAck::New(::google::protobuf::Arena* arena) const {
  ProtoAck* n = new ProtoAck;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ProtoAck::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.ProtoAck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ciphertext_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ProtoAck::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.ProtoAck)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes CipherText = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_ciphertext()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.ProtoAck)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.ProtoAck)
  return false;
#undef DO_
}

void ProtoAck::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.ProtoAck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes CipherText = 1;
  if (this->ciphertext().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->ciphertext(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.ProtoAck)
}

::google::protobuf::uint8* ProtoAck::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protocol.ProtoAck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes CipherText = 1;
  if (this->ciphertext().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->ciphertext(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.ProtoAck)
  return target;
}

size_t ProtoAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.ProtoAck)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes CipherText = 1;
  if (this->ciphertext().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->ciphertext());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProtoAck::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.ProtoAck)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtoAck* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ProtoAck>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.ProtoAck)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.ProtoAck)
    MergeFrom(*source);
  }
}

void ProtoAck::MergeFrom(const ProtoAck& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.ProtoAck)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ciphertext().size() > 0) {

    ciphertext_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ciphertext_);
  }
}

void ProtoAck::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.ProtoAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtoAck::CopyFrom(const ProtoAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.ProtoAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoAck::IsInitialized() const {
  return true;
}

void ProtoAck::Swap(ProtoAck* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtoAck::InternalSwap(ProtoAck* other) {
  using std::swap;
  ciphertext_.Swap(&other->ciphertext_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ProtoAck::GetMetadata() const {
  protobuf_proto_5fhs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_5fhs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ProtoHeartBeat::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ProtoHeartBeat::kTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ProtoHeartBeat::ProtoHeartBeat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_proto_5fhs_2eproto::InitDefaultsProtoHeartBeat();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:protocol.ProtoHeartBeat)
}
ProtoHeartBeat::ProtoHeartBeat(const ProtoHeartBeat& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  timestamp_ = from.timestamp_;
  // @@protoc_insertion_point(copy_constructor:protocol.ProtoHeartBeat)
}

void ProtoHeartBeat::SharedCtor() {
  timestamp_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

ProtoHeartBeat::~ProtoHeartBeat() {
  // @@protoc_insertion_point(destructor:protocol.ProtoHeartBeat)
  SharedDtor();
}

void ProtoHeartBeat::SharedDtor() {
}

void ProtoHeartBeat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ProtoHeartBeat::descriptor() {
  ::protobuf_proto_5fhs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_5fhs_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ProtoHeartBeat& ProtoHeartBeat::default_instance() {
  ::protobuf_proto_5fhs_2eproto::InitDefaultsProtoHeartBeat();
  return *internal_default_instance();
}

ProtoHeartBeat* ProtoHeartBeat::New(::google::protobuf::Arena* arena) const {
  ProtoHeartBeat* n = new ProtoHeartBeat;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ProtoHeartBeat::Clear() {
// @@protoc_insertion_point(message_clear_start:protocol.ProtoHeartBeat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  timestamp_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool ProtoHeartBeat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protocol.ProtoHeartBeat)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // sfixed64 Timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_SFIXED64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protocol.ProtoHeartBeat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protocol.ProtoHeartBeat)
  return false;
#undef DO_
}

void ProtoHeartBeat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protocol.ProtoHeartBeat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sfixed64 Timestamp = 1;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSFixed64(1, this->timestamp(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protocol.ProtoHeartBeat)
}

::google::protobuf::uint8* ProtoHeartBeat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protocol.ProtoHeartBeat)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // sfixed64 Timestamp = 1;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSFixed64ToArray(1, this->timestamp(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protocol.ProtoHeartBeat)
  return target;
}

size_t ProtoHeartBeat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protocol.ProtoHeartBeat)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // sfixed64 Timestamp = 1;
  if (this->timestamp() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ProtoHeartBeat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protocol.ProtoHeartBeat)
  GOOGLE_DCHECK_NE(&from, this);
  const ProtoHeartBeat* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ProtoHeartBeat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protocol.ProtoHeartBeat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protocol.ProtoHeartBeat)
    MergeFrom(*source);
  }
}

void ProtoHeartBeat::MergeFrom(const ProtoHeartBeat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protocol.ProtoHeartBeat)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
}

void ProtoHeartBeat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protocol.ProtoHeartBeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ProtoHeartBeat::CopyFrom(const ProtoHeartBeat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protocol.ProtoHeartBeat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProtoHeartBeat::IsInitialized() const {
  return true;
}

void ProtoHeartBeat::Swap(ProtoHeartBeat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ProtoHeartBeat::InternalSwap(ProtoHeartBeat* other) {
  using std::swap;
  swap(timestamp_, other->timestamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ProtoHeartBeat::GetMetadata() const {
  protobuf_proto_5fhs_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_proto_5fhs_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol

// @@protoc_insertion_point(global_scope)
