// Code generated by "stringer -type ActivePerformState"; DO NOT EDIT.

package db

import "fmt"

const _ActivePerformState_name = "E_ACTIVEPERFORMSTATE_WAITINGE_ACTIVEPERFORMSTATE_RUNNINGE_ACTVIEPERFROMSTATE_COMPLETED"

var _ActivePerformState_index = [...]uint8{0, 28, 56, 86}

func (i ActivePerformState) String() string {
	if i < 0 || i >= ActivePerformState(len(_ActivePerformState_index)-1) {
		return fmt.Sprintf("ActivePerformState(%d)", i)
	}
	return _ActivePerformState_name[_ActivePerformState_index[i]:_ActivePerformState_index[i+1]]
}
