// Code generated by "stringer -type=SessionState"; DO NOT EDIT.

package transport

import "fmt"

const _SessionState_name = "E_SESSIONSTATE_VERIFIY_SYNE_SESSIONSTATE_VERIFIY_ACKE_SESSIONSTATE_CONNECTED"

var _SessionState_index = [...]uint8{0, 26, 52, 76}

func (i SessionState) String() string {
	if i < 0 || i >= SessionState(len(_SessionState_index)-1) {
		return fmt.Sprintf("SessionState(%d)", i)
	}
	return _SessionState_name[_SessionState_index[i]:_SessionState_index[i+1]]
}
