// Code generated by "stringer -type=SessionCmd"; DO NOT EDIT.

package transport

import "fmt"

const _SessionCmd_name = "E_SESSIONCMD_STARTCONNE_SESSIONCMD_STOPCONNE_SESSIONCMD_ACTIVESTOPCONNE_SESSIONCMD_TRANSFER"

var _SessionCmd_index = [...]uint8{0, 22, 43, 70, 91}

func (i SessionCmd) String() string {
	if i < 0 || i >= SessionCmd(len(_SessionCmd_index)-1) {
		return fmt.Sprintf("SessionCmd(%d)", i)
	}
	return _SessionCmd_name[_SessionCmd_index[i]:_SessionCmd_index[i+1]]
}
