// Code generated by "stringer -type DoyoRecDataCmdType"; DO NOT EDIT.

package proto

import "strconv"

const _DoyoRecDataCmdType_name = "DoyoRecDataCmdUserLoginDoyoRecDataCmdUserLogoutDoyoRecDataCmdAnchorStartRoomDoyoRecDataCmdAnchorStopRoomDoyoRecDataCmdEnterRoomDoyoRecDataCmdLeaveRoomDoyoRecDataCmdAddFriendsDoyoRecDataCmdAddFollowDoyoRecDataCmdDelFollow"

var _DoyoRecDataCmdType_index = [...]uint8{0, 23, 47, 76, 104, 127, 150, 174, 197, 220}

func (i DoyoRecDataCmdType) String() string {
	if i < 0 || i >= DoyoRecDataCmdType(len(_DoyoRecDataCmdType_index)-1) {
		return "DoyoRecDataCmdType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DoyoRecDataCmdType_name[_DoyoRecDataCmdType_index[i]:_DoyoRecDataCmdType_index[i+1]]
}
