// Code generated by "stringer -type=SessionPeekState"; DO NOT EDIT.

package transport

import "fmt"

const _SessionPeekState_name = "E_SESSIONPEEKSTATE_HEADE_SESSIONPEEKSTATE_WHOLE"

var _SessionPeekState_index = [...]uint8{0, 23, 47}

func (i SessionPeekState) String() string {
	if i < 0 || i >= SessionPeekState(len(_SessionPeekState_index)-1) {
		return fmt.Sprintf("SessionPeekState(%d)", i)
	}
	return _SessionPeekState_name[_SessionPeekState_index[i]:_SessionPeekState_index[i+1]]
}
