// Code generated by "stringer -type=SessionState"; DO NOT EDIT.

package transport

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[E_SESSIONSTATE_VERIFIY_SYN-0]
	_ = x[E_SESSIONSTATE_VERIFIY_ACK-1]
	_ = x[E_SESSIONSTATE_CONNECTED-2]
}

const _SessionState_name = "E_SESSIONSTATE_VERIFIY_SYNE_SESSIONSTATE_VERIFIY_ACKE_SESSIONSTATE_CONNECTED"

var _SessionState_index = [...]uint8{0, 26, 52, 76}

func (i SessionState) String() string {
	if i < 0 || i >= SessionState(len(_SessionState_index)-1) {
		return "SessionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SessionState_name[_SessionState_index[i]:_SessionState_index[i+1]]
}
