// Code generated by "stringer -type=NetErrorType net.go"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NETERR_TYPE_NO-0]
	_ = x[NETERR_TYPE_DNSERROR-1]
	_ = x[NETERR_TYPE_INVALIDADDERROR-2]
	_ = x[NETERR_TYPE_UNKNOWNNETWORKERROR-3]
	_ = x[NETERR_TYPE_ADDERROR-4]
	_ = x[NETERR_TYPE_DNSCONFIGERROR-5]
	_ = x[NETERR_TYPE_OS_SYSCALLERROR-6]
}

const _NetErrorType_name = "NETERR_TYPE_NONETERR_TYPE_DNSERRORNETERR_TYPE_INVALIDADDERRORNETERR_TYPE_UNKNOWNNETWORKERRORNETERR_TYPE_ADDERRORNETERR_TYPE_DNSCONFIGERRORNETERR_TYPE_OS_SYSCALLERROR"

var _NetErrorType_index = [...]uint8{0, 14, 34, 61, 92, 112, 138, 165}

func (i NetErrorType) String() string {
	if i < 0 || i >= NetErrorType(len(_NetErrorType_index)-1) {
		return "NetErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NetErrorType_name[_NetErrorType_index[i]:_NetErrorType_index[i+1]]
}
