package errorcode

const (
	ERROR_CODE_DEFAULT = -1

	ERROR_CODE_NOT_ENOUGH_GEM              = -701     // 钻石不够
	ERROR_CODE_NOT_ENOUGH_RESOURCE         = -6000002 // 资源不够
	ERROR_CODE_NOT_ENOUGH_BATTLE_SHIP_CARD = -6000003 // 战舰碎片不足
	ERROR_CODE_NOT_ENOUGH_PROP             = -6000004 // 道具数量不足
	ERROR_CODE_NOT_ENOUGH_WEAPON_CARD      = -6000005 // 武器卡片不足
	ERROR_CODE_NOT_ENOUGH_SHIP_SOUL        = -6000006 // 舰魂不够

	ERROR_CODE_BATTLE_SHIP_NOT_EXSIT              = -6001001 // 船不存在
	ERROR_CODE_BATTLE_SHIP_LEVEL_LIMIT            = -6001002 // 船已经达到等级上限
	ERROR_CODE_BATTLE_SHIP_STAR_LEVEL_LIMIT       = -6001003 // 船已经达到星级上限
	ERROR_CODE_BATTLE_SHIP_NOT_ENOUGH_CARD        = -6001004 // 船升级碎片不足
	ERROR_CODE_BATTLE_SHIP_LEVEL_REACH_STAR_LIMIT = -6001005 // 船的等级超过星级上线
	ERROR_CODE_BATTLE_SHIP_STAR_REACH_LEVEL_LIMIT = -6001006 // 船的星级超过等级上线
	ERROR_CODE_BATTLE_SHIP_IS_NOT_CARD_TYPE       = -6001007 // 船不是碎片形态

	ERROR_CODE_CAMPAIGN_PRODUCE_RESOURCE_TIME_NOT_COMMING = -7001001 // 不到领取资源的时间
	ERROR_CODE_CAMPAIGN_PRODUCE_RESOURCE_ALREAY_INIT      = -7001002 // 已经初始化领取资源

	ERROR_CODE_CAMPAIGN_EVENT_EXPIRED    = -7002001 // 事件已过期
	ERROR_CODE_CAMPAIGN_EVENT_UNFINISHED = -7002002 // 事件进度未满
	ERROR_CODE_CAMPAIGN_EVENT_NOT_EXSIT  = -7002003 // 事件不存在
	ERROR_CODE_CAMPAIGN_EVENT_CLOSED     = -7002004 // 事件已关闭
	ERROR_CODE_CAMPAIGN_EVENT_FINISHED   = -7002005 // 事件已完成

	ERROR_CODE_CAMPAIGN_ID_NOT_EXIST = -7003001 // 关卡不存在

	ERROR_CODE_CAMPAIGN_PLOT_ALREADY_PASSED = -7004001 // PVE剧情已经通过

	ERROR_CODE_ACTIVITY_TASK_ID_NOT_EXIST = -8001001 // 日常任务不存在
	ERROR_CODE_ACTIVITY_TASK_UNFINISHED   = -8001002 // 任务未完成，不能领取奖励
	ERROR_CODE_ACTIVITY_TASK_FINISHED     = -8001003 // 任务已完成过了，不能领取奖励

	ERROR_CODE_ACTIVITY_SCORE_REWARD_ID_NOT_EXIST    = -8002001 // 活跃度奖励ID不存在
	ERROR_CODE_ACTIVITY_SCORE_REWARD_NOT_REACH       = -8002002 // 活跃度奖励分数未达到
	ERROR_CODE_ACTIVITY_SCORE_REWARD_RECEIVED_REPEAT = -8002003 // 活跃度奖励已领取

	ERROR_CODE_GROWUP_TASK_ID_NOT_EXIST           = -8003001 // 成长任务Id不存在
	ERROR_CODE_GROWUP_TASK_NOT_REACH              = -8003002 // 成长任务未完成
	ERROR_CODE_GROWUP_TASK_REWARD_RECEIVED_REPEAT = -8003003 // 成长任务奖励已领取

	ERROR_CODE_GUILD_NAME_LENGTH_INVALID             = -9001001 // 公会名字过长
	ERROR_CODE_GUILD_JOIN_TYPE_ERROR                 = -9001002 // 公会加入类型错误
	ERROR_CODE_GUILD_DESC_TOO_LONG                   = -9001003 // 公会描述文字过长
	ERROR_CODE_GUILD_PLAYER_LEVEL_NOT_REACH          = -9001004 // 等级不足
	ERROR_CODE_GUILD_ALREADY_IN_GUILD                = -9001005 // 已经有公会了
	ERROR_CODE_GUILD_NOT_IN_GUILD                    = -9001006 // 不在公会中
	ERROR_CODE_GUILD_ID_NOT_EXIST                    = -9001007 // 公会Id不存在
	ERROR_CODE_GUILD_ID_FORMAT_WRONG                 = -9001008 // 公会Id格式错误
	ERROR_CODE_GUILD_MEMBER_FULL                     = -9001009 // 公会成员已满
	ERROR_CODE_GUILD_DENY_ANYONE                     = -9001010 // 公会拒绝任何人加入
	ERROR_CODE_GUILD_PERMISSION_DENIED               = -9001011 // 公会操作权限不足
	ERROR_CODE_GUILD_LEAGUE_LEVEL_NOT_REACH          = -9001012 // 联赛等级不足
	ERROR_CODE_GUILD_ALREADY_IN_THIS_GUILD           = -9001013 // 已在当前公会中
	ERROR_CODE_GUILD_NOT_IN_THIS_GUILD               = -9001014 // 不在当前公会中
	ERROR_CODE_GUILD_JOIN_NEED_WAIT                  = -9001015 // 需要等待再次加入公会的冷却时间过去
	ERROR_CODE_GUILD_POST_TYPE_ERROR                 = -9001016 // 公会职位类型错误
	ERROR_CODE_GUILD_POST_FULL                       = -9001017 // 该职位成员已满
	ERROR_CODE_GUILD_APPLY_REPEAT                    = -9001018 // 重复申请
	ERROR_CODE_GUILD_APPLY_NOT_EXIST                 = -9001019 // 公会申请不存在
	ERROR_CODE_GUILD_INVITE_REPEAT                   = -9001020 // 公会邀请已存在
	ERROR_CODE_GUILD_INVITE_NOT_EXIST                = -9001021 // 公会邀请不存在
	ERROR_CODE_GUILD_JOIN_TYPE_NOT_ALLOW_ANYONE      = -9001022 // 公会加入类型不是允许任何人加入
	ERROR_CODE_GUILD_JOIN_TYPE_NOT_NEED_AUDIT        = -9001023 // 公会加入类型不是需要审批
	ERROR_CODE_GUILD_TASK_REWARD_VITALITY_NOT_ENOUGH = -9001024 // 活跃度不够，不能领取奖励
	ERROR_CODE_GUILD_TASK_REWARD_ALREADY_RECEIVED    = -9001025 // 已经领取过奖励了
	ERROR_CODE_GUILD_PROP_NOT_ENOUGH                 = -9001026 // 道具数量不够
	ERROR_CODE_GUILD_IN_WAR                          = -9001027 // 公会战期间，玩家不能退出或者被踢出公会

	ERROR_CODE_SALVAGE_NOT_ENOUGH_TIMES = -9002001 // 打捞次数不够
	ERROR_CODE_SALVAGE_NOT_ENOUGH_NETS  = -9002002 // 打捞网不够

	ERROR_CODE_RELICS_NOT_ENOUGH_PIECES        = -9003001 // 碎片不够
	ERROR_CODE_RELICS_PIECES_ALREADY_INSTALLED = -9003002 // 该上古遗物碎片已经安装过了
	ERROR_CODE_RELICS_UNCOMPLETED              = -9003003 // 上古遗物未完全装好
	ERROR_CODE_RELICS_ALREADY_COMPLETED        = -9003004 // 上古遗物碎片都已装好
	ERROR_CODE_RELICS_ALREADY_RECEIVED         = -9003005 // 上古遗物奖励已领取
)
