package config

const (
	MISSION_TYPE_LEAGUE_PVP_TIMES                     = "league_pvp_times"
	MISSION_TYPE_LEAGUE_PVP_WIN_TIMES                 = "league_pvp_win_times"
	MISSION_TYPE_CAMPAIGN_BATTLE_TIMES                = "campaign_battle_times"
	MISSION_TYPE_CAMPAIGN_CLAIM_RESOURCES_TIMES       = "campaign_claim_resources_times"
	MISSION_TYPE_LEAGUE_PVP_SINK_BATTLE_SHIPS         = "league_pvp_sink_battleships"
	MISSION_TYPE_LEAGUE_PVP_COMBO_TIMES               = "league_pvp_combo_times"
	MISSION_TYPE_SHOP_BUY_CARDPACKS                   = "shop_buy_cardpacks"
	MISSION_TYPE_SOCIAL_SHARE_TIMES                   = "social_share_times"
	MISSION_TYPE_CONSUME_GEM_COUNT                    = "consume_gem_count"
	MISSION_TYPE_PLAYER_LEVEL_UP                      = "player_levelup"
	MISSION_TYPE_BATTLE_SHIP_LEVEL_UP                 = "battleship_levelup"
	MISSION_TYPE_BATTLE_SHIP_STRENGTHEN               = "battleship_strengthen"
	MISSION_TYPE_FRIGATE_LEVEL_UP                     = "frigate_levelup"
	MISSION_TYPE_COLLECT_BATTLE_SHIP                  = "collect_battleship"
	MISSION_TYPE_FRIGATE_SPELL_LEVEL_UP               = "frigate_spell_levelup"
	MISSION_TYPE_FRIGATE_WEAPON_LEVEL_UP              = "frigate_weapon_levelup"
	MISSION_TYPE_CAMPAIGN_PASS_LEVEL                  = "campaign_pass_level"
	MISSION_TYPE_LEAGUE_LEVEL_UP                      = "league_levelup"
	MISSION_TYPE_CAMPAIGN_COLLECT_RESOURCES           = "campaign_collect_resources"
	MISSION_TYPE_LEAGUE_PVP_COMBO_REACH_HISTORY       = "league_pvp_combo_reach_history"
	MISSION_TYPE_LEAGUE_PVP_TIMES_HISTORY             = "league_pvp_times_history"
	MISSION_TYPE_LEAGUE_LEVEL_REACH                   = "league_level_reach"
	MISSION_TYPE_FRIGATE_WEPON_KO_RIVAL               = "frigate_weapon_ko_rival"
	MISSION_TYPE_LEAGUE_PVP_DRAW                      = "league_pvp_draw"
	MISSION_TYPE_LEAGUE_PVP_WEAK_DEFEAT_STRONG        = "league_pvp_weak_defeat_strong"
	MISSION_TYPE_GUILD_CHAIRMAIN                      = "guild_chairman"
	MISSION_TYPE_ACTIVITY_SCORE_OVERFLOW_CONTINUOUS   = "activity_score_overflow_continuous"
	MISSION_TYPE_GAIN_LEGEND_CARD                     = "gain_legend_card"
	MISSION_TYPE_LEAGUE_PVP_WIN_STREAK                = "league_pvp_win_streak"
	MISSION_TYPE_LEAGUE_PVP_WIN_STREAK_WITH_MAIN_SHIP = "league_pvp_win_streak_with_main_lineup"
	MISSION_TYPE_CAMPAIGN_PASS_CHAPTER_HISTORY        = "campaign_pass_chapter_history"
	MISSION_TYPE_CAMPAIGN_COMPLETE_EVENT              = "campaign_complete_event"
	MISSION_TYPE_TEACHING_CHAPTER_COMPLETE_HISTORY    = "teaching_chapter_complete_history"
	MISSION_TYPE_LOGIN_CONTINUOUS                     = "login_continuous"
	MISSION_TYPE_BREAK_OUT_ALL                        = "breakout_all"
	MISSION_TYPE_TUTORIAL_COMPLETE_HISTORY            = "tutorial_complete_history"
	MISSION_TYPE_GAIN_ALL_BATTLE_SHIPS                = "gain_all_battleships"
	MISSION_TYPE_GAIN_ALL_ACHIEVEMENTS                = "gain_all_achievements"
	MISSION_TYPE_FIRST_PURCHASE                       = "first_purchase"
	MISSION_TYPE_SALVAGE                              = "salvage"
	MISSION_TYPE_DAILY_LOGIN                          = "daily_login"
)

const (
	MISSION_PARAMETER_TARGET         = "target"
	MISSION_PARAMETER_CARDPACK_ID    = "cardpack_id"
	MISSION_PARAMETER_LEVEL          = "level"
	MISSION_PARAMETER_STAR_LEVEL     = "star_level"
	MISSION_PARAMETER_QUALITY        = "quality"
	MISSION_PARAMETER_SPELL_ID       = "spell_id"
	MISSION_PARAMETER_CHAPTER        = "chapter"
	MISSION_PARAMETER_RESOURCE_TYPE  = "resource_type"
	MISSION_PARAMETER_LEAGUE_LEVEL   = "league_level"
	MISSION_PARAMETER_ACTIVITY_SCORE = "activity_score"
	MISSION_PARAMETER_DAYS           = "days"
	MISSION_PARAMETER_WEAPON_ID      = "weapon_id"
	MISSION_PARAMETER_COMBO          = "combo"
)
