// Code generated by "stringer -type RouterSvrDispatchPolicy"; DO NOT EDIT.

package proto

import "strconv"

const _RouterSvrDispatchPolicy_name = "RouterSvrDispatchPolicyRandomRouterSvrDispatchPolicyRRRouterSvrDispatchPolicyDHRouterSvrDispatchPolicyBrdRouterSvrDispatchPolicyBrdMSRouterSvrDispatchPolicyBrdMasterRouterSvrDispatchPolicyBrdSlaveRouterSvrDispatchPolicyLoad"

var _RouterSvrDispatchPolicy_index = [...]uint8{0, 29, 54, 79, 105, 133, 165, 196, 223}

func (i RouterSvrDispatchPolicy) String() string {
	if i < 0 || i >= RouterSvrDispatchPolicy(len(_RouterSvrDispatchPolicy_index)-1) {
		return "RouterSvrDispatchPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RouterSvrDispatchPolicy_name[_RouterSvrDispatchPolicy_index[i]:_RouterSvrDispatchPolicy_index[i+1]]
}
