// Code generated by "stringer -type ServTypeMatchPolicy"; DO NOT EDIT.

package proto

import "strconv"

const _ServTypeMatchPolicy_name = "ServTypeMatchPolicyStrictServtypeMatchPolicyPrefix"

var _ServTypeMatchPolicy_index = [...]uint8{0, 25, 50}

func (i ServTypeMatchPolicy) String() string {
	if i < 0 || i >= ServTypeMatchPolicy(len(_ServTypeMatchPolicy_index)-1) {
		return "ServTypeMatchPolicy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServTypeMatchPolicy_name[_ServTypeMatchPolicy_index[i]:_ServTypeMatchPolicy_index[i+1]]
}
